/**
 * Type definitions for smiles-drawer
 */

/**
 * Represents an atom in a bracket notation with detailed properties.
 * This matches the IBracket interface from Atom.ts
 */
export interface BracketAtom {
  element: string;
  isotope?: number;
  charge?: ("--" | "-" | "+" | "++")[];
  hcount?: number;
  chirality?: string;
  class?: number;
  [key: string]: any;
}

/**
 * Represents a node in the SMILES parse tree.
 * This structure is generated by the PEG.js parser.
 */
export interface ParseTreeNode {
  /** The atom at this node - either a simple string or a bracket atom object */
  atom: string | BracketAtom;
  /** The bond type leading to this atom (-, =, #, etc.) */
  bond: string;
  /** The bond type for a branch connection */
  branchBond?: string;
  /** Array of branch nodes */
  branches: ParseTreeNode[];
  /** Number of branches at this node */
  branchCount: number;
  /** Array of ring bond identifiers */
  ringbonds: any[];
  /** Number of ring bonds at this node */
  ringbondCount: number | boolean;
  /** The next node in the main chain */
  next: ParseTreeNode | null;
  /** Whether this node has a next node */
  hasNext: boolean;
  /** Whether this atom is in bracket notation */
  isBracket?: boolean | string;
}

/**
 * Represents a 2D adjacency matrix for graph operations.
 */
export type AdjacencyMatrix = number[][];

/**
 * Represents a distance matrix for graph operations.
 */
export type DistanceMatrix = number[][];

/**
 * Represents an adjacency list for graph operations.
 */
export type AdjacencyList = number[][];

/**
 * Represents a bridge in a graph (an edge whose removal increases connected components).
 */
export type Bridge = [number, number];
